### ISSUE TITLE
Implement SQLite

### ISSUE THREAD

**Issue by anishap16** [nhan0504/CS326#78]
**Feature Name**: Implement SQLite

**Description**:

Set up SQLite for the web application

**Point Value**: 6

**Size Category**: Large

**Owner**: Anisha Prathi

**Comment by AshleyMcN** [comment]
Does this also include setting up the Express.js server work?

**Comment by nhan0504** [comment]
Look good to me

**Comment by liamkaigates** [comment]
Liam Gates on November 21, 2024: Looks good.

**Comment by hungumass** [comment]
Looks good to me!

**Comment by KhanhLeBigWow** [comment]
Sounds good!

**Comment by nhan0504** [comment]
Merged
