### ISSUE TITLE
Fetch Outfits

### ISSUE THREAD

**Issue by anishap16** [nhan0504/CS326#79]
**Feature Name**: Fetch Outfits

**Description**:

Fetch outfits currently stored in SQLite and display in log page

**Point Value**: 5

**Size Category**: Large

**Owner**: Anisha Prathi

**Comment by sophia-hubscher** [comment]
Looks good! This task shouldn't be too complicated, since we're just going to be referencing wardrobe items with IDs

**Comment by AshleyMcN** [comment]
Sounds good!

**Comment by hungumass** [comment]
This looks nice!

**Comment by liamkaigates** [comment]
Liam Gates on November 21, 2024: Looks good.

**Comment by KhanhLeBigWow** [comment]
Sounds good!
