### ISSUE TITLE
User Authentication with Google Auth

### ISSUE THREAD

**Issue by sophia-hubscher** [nhan0504/CS326#80]
**Feature Name**: User Authentication with Google Auth

**Description**:

This feature will implement secure user authentication using Google authentication. When users are logged in, the login button at the top of the screen will update, and they will be able to view their own wardrobe items, outfits, statistics, and suggestions. When users are not logged in, they will not be able to use wardrobe or outfit functionality and will be prompted to log in.

**Point Value**: 5

**Size Category**: Large

**Owner**: Sophia Hubscher

**Comment by anishap16** [comment]
What's your reasoning for using Google authentication specifically?

**Comment by AshleyMcN** [comment]
I think Google Authentication is a great idea!

**Comment by sophia-hubscher** [comment]
> What's your reasoning for using Google authentication specifically?

Google authentication adds an extra layer of security, and I assume most people already have a Google account, so it seemed like a good choice. If we have issues setting it up though, we can always switch over to using the other authentication method shown in class

**Comment by KhanhLeBigWow** [comment]
I think that's a good idea!

**Comment by sophia-hubscher** [comment]
**Decision:** We will include this feature as planned. I will implement Google authentication. The team agreed to include a URL rewrite to redirect users to the login page if they access any page without logging in.
