### ISSUE TITLE
Fetch Wardrobe Items

### ISSUE THREAD

**Issue by AshleyMcN** [nhan0504/CS326#81]
This feature will implement a GET request for wardrobe items from the database and display the items in the wardrobe page as well as the log page add item form. This will involve fetching images.
**Point Value**: 6 points
**Size Category**: Large
**Owner**: Ashley McNamara

**Comment by sophia-hubscher** [comment]
For fetching images, can we reuse our Base64 logic from the past milestone?

**Comment by anishap16** [comment]
Yes, I think that's a good idea!

**Comment by nhan0504** [comment]
This is good

**Comment by AshleyMcN** [comment]
> For fetching images, can we reuse our Base64 logic from the past milestone?

Yes, we should be able to reuse this logic.

**Comment by hungumass** [comment]
Looks good to me!

**Comment by liamkaigates** [comment]
Liam Gates on November 21, 2024: Looks good.

**Comment by KhanhLeBigWow** [comment]
I think that's a good idea!

**Comment by AshleyMcN** [comment]
Decision: We will include this feature as planned.
