### ISSUE TITLE
Delete wardrobe items

### ISSUE THREAD

**Issue by sophia-hubscher** [nhan0504/CS326#82]
Feature Name: Delete wardrobe items

Description:

When users click the delete button on an individual wardrobe item, that wardrobe item currently stored in SQLite will be removed from the database and this deletion will be reflected in the front-end.

Point Value: 5

Size Category: Large

Owner: Bruce Le

**Comment by AshleyMcN** [comment]
Sounds good to me!

**Comment by anishap16** [comment]
I agree with using event listeners!

**Comment by liamkaigates** [comment]
Liam Gates on November 21, 2024: Looks good.

**Comment by KhanhLeBigWow** [comment]
Looks good to me
