### ISSUE TITLE
Add Wardrobe Items

### ISSUE THREAD

**Issue by AshleyMcN** [nhan0504/CS326#83]
**Add Wardrobe Item**
**Description:** This feature will implement a POST request to the database to store a new wardrobe item. This includes storing an image. This will connect to the add wardrobe item form and then will publish an event that is listened for by every other page.
**Tag:** #83
**Owner:** Abby Tran
**Expected Outcome:** A function endpoint for adding item to the wardrobe and tested with Postman

**Comment by sophia-hubscher** [comment]
Looks good! Like for fetching images, can we reuse our Base64 logic from the past milestone?

**Comment by AshleyMcN** [comment]
> Looks good! Like for fetching images, can we reuse our Base64 logic from the past milestone?

We should be able to reuse this logic.

**Comment by liamkaigates** [comment]
Liam Gates on November 21, 2024: Looks good.

**Comment by hungumass** [comment]
Looks good!

**Comment by KhanhLeBigWow** [comment]
Looks great!
