### ISSUE TITLE
 Store Outfit

### ISSUE THREAD

**Issue by hungumass** [nhan0504/CS326#85]
This feature will implement a POST request to the database to store a new outfit item. This includes storing multiple images for multiple wardrobe items. This will connect to the add outfit form and then will publish an event that is listened for by every other page.
Point Value: 6 points
Size Category: Large
Owner: Hung Nguyen

**Comment by nhan0504** [comment]
Look good to me

**Comment by anishap16** [comment]
Looks good to me!

**Comment by KhanhLeBigWow** [comment]
Looks great!
