### ISSUE TITLE
Update Wardrobe Item

### ISSUE THREAD

**Issue by liamkaigates** [nhan0504/CS326#86]
**Feature Name**: Update Wardrobe Item

**Description**:

The user will be able to update the settings of their wardrobe item, such as the favorite setting of the item. This will allow the user to keep their digital wardrobe up to date with respect to their physical wardrobe. This feature will be integrated in the wardrobe view component, while connected to IndexedDB and SQLite. It must be able to update the database with the updated item along with updating the UI.

**Point Value**: 5

**Size Category**: Large

**Owner**: Liam Gates

**Comment by AshleyMcN** [comment]
This will also be used when we increase the number of times worn for an item in the log page. Sounds good!

**Comment by sophia-hubscher** [comment]
Looks great!

**Comment by hungumass** [comment]
This seems good to me!

**Comment by KhanhLeBigWow** [comment]
Looks great!

**Comment by nhan0504** [comment]
Looks good to me

**Comment by liamkaigates** [comment]
It has been decided to include the feature in the application.
