### ISSUE TITLE
Suggestions page data aggregation

### ISSUE THREAD

**Issue by sophia-hubscher** [nhan0504/CS326#89]
**Feature Name:** Suggestions page data aggregation

**Description:**

This feature will take the wardrobe items used in suggestions and create suggested outfits with them. Users can indicate if they would like to prioritize underutilized pieces and using that information, this back-end method will return a list of suggested outfits.

**Point Value:** 5

**Size Category:** Large

**Owner:** Sophia Hubscher

**Comment by AshleyMcN** [comment]
I think the filtering is a separate task right? This should just be the logic to actually put the outfits together

**Comment by nhan0504** [comment]
Looking good

**Comment by liamkaigates** [comment]
Liam Gates on November 22, 2024: Looks good.

**Comment by sophia-hubscher** [comment]
@anishap16 and @KhanhLeBigWow, any comments from you two before we reach a final decision on this issue?

**Comment by KhanhLeBigWow** [comment]
Looks good to me

**Comment by anishap16** [comment]
Looks good to me!

**Comment by sophia-hubscher** [comment]
**Decision:** We will include this feature as planned. I will implement suggestions page data aggregation. The team agreed to have this back-end method return a list of suggested outfits based on user preferences. Filtering will be handled in a separate issue.
