### ISSUE TITLE
Suggestions Page Routes and Endpoints

### ISSUE THREAD

**Issue by AshleyMcN** [nhan0504/CS326#90]
This feature will implement the routes and endpoints for the suggestions page to fetch the data. This will then connect to the front-end of the suggestions page to properly display the new results that are now being constructed on the backend.
Point Value: 5 points
Size Category: Large
Owner: Ashley McNamara

**Comment by sophia-hubscher** [comment]
This looks great! If you have any questions about the stats or suggestion page code, feel free to ask Abby and I over Slack!

**Comment by hungumass** [comment]
LGTM!

**Comment by nhan0504** [comment]
This is good

**Comment by liamkaigates** [comment]
Liam Gates on November 22, 2024: Looks good.

**Comment by AshleyMcN** [comment]
Decision: We will include this feature as planned.
