### ISSUE TITLE
Stats page data aggregation

### ISSUE THREAD

**Issue by nhan0504** [nhan0504/CS326#91]
**Description:**
This feature will implement endpoint that fetch data from the database and perform some data aggregation and calculation so that the state page can display it

**Point Value:** 5 points

**Size Category:** Large

**Owner:** Abby Tran

**Comment by AshleyMcN** [comment]
> I think the endpoint is a separate task. Do we want this issue to just focus on aggregation and calculation instead?

Yeah my task includes implementing the endpoint. This one should just be doing all the calculations and stuff to get the stats

**Comment by hungumass** [comment]
Other than what was mentioned, I think this is good!

**Comment by liamkaigates** [comment]
Liam Gates on November 22, 2024: Looks good.
