### ISSUE TITLE
Suggestions page filter bar 

### ISSUE THREAD

**Issue by hungumass** [nhan0504/CS326#92]
This feature will implement suggestions page filter bar and the wardrobe at the backend to fetch the data. This will then connect to the front-end of the suggestions page to display the new results that are constructed.
Point Value: 5 points
Size Category: Large
Owner: Hung Nguyen

**Comment by AshleyMcN** [comment]
I don't think this task has to do with the wardrobe, I think that is another task. Other than that sounds good!

**Comment by sophia-hubscher** [comment]
Other than what Ashley said, this looks perfect!

**Comment by nhan0504** [comment]
Looks good to me
