### ISSUE TITLE
Log Page Filter Bar

### ISSUE THREAD

**Issue by liamkaigates** [nhan0504/CS326#93]
**Feature Name**: Log Page Filter Bar

**Description**:

The user will be able to filter the outfits on the Log page using different properties of the outfit, such as the occasion of the outfit. This will allow the user to organize and select their outfits using different properties of the outfit. This feature will be integrated in the Log page view component, while connected to IndexedDB and SQLite. It must be able to get the filtered data from the database along with updating the UI components.

**Point Value**: 5

**Size Category**: Large

**Owner**: Liam Gates

**Comment by AshleyMcN** [comment]
Sounds good!

**Comment by sophia-hubscher** [comment]
Looks great!

**Comment by nhan0504** [comment]
Looks good

**Comment by hungumass** [comment]
Looks good!
